export { default as App } from "./App";
export { default as Contacts } from "./Contacts";
export { default as Education } from "./Education";
export { default as Experience } from "./Experience";
export { default as Profile } from "./Profile";
export { default as Skills } from "./Skills";
export { default as SectionTitle } from "./SectionTitle";
export { default as Timeline } from "./Timeline";
export { default as Learning } from "./Learning";
